  // light theme for testing purposes
  // feel free to uncomment to get flash banged lol
  // op's opinion I thik it looks good :)
  // included in js files to have continuity lmao
const theme = {
  background: "#f4fafb",
  error: "#ba1a1a",
  error_container: "#ffdad6",
  inverse_on_surface: "#ecf2f2",
  inverse_primary: "#80d4da",
  inverse_surface: "#2b3232",
  on_background: "#161d1d",
  on_error: "#ffffff",
  on_error_container: "#410002",
  on_primary: "#ffffff",
  on_primary_container: "#002022",
  on_primary_fixed: "#002022",
  on_primary_fixed_variant: "#004f53",
  on_secondary: "#ffffff",
  on_secondary_container: "#041f21",
  on_secondary_fixed: "#041f21",
  on_secondary_fixed_variant: "#324b4d",
  on_surface: "#161d1d",
  on_surface_variant: "#3f4949",
  on_tertiary: "#ffffff",
  on_tertiary_container: "#091b36",
  on_tertiary_fixed: "#091b36",
  on_tertiary_fixed_variant: "#374764",
  outline: "#6f7979",
  outline_variant: "#bec8c9",
  primary: "#00696e",
  primary_container: "#9cf0f6",
  primary_fixed: "#9cf0f6",
  primary_fixed_dim: "#80d4da",
  scrim: "#000000",
  secondary: "#4a6365",
  secondary_container: "#cce8e9",
  secondary_fixed: "#cce8e9",
  secondary_fixed_dim: "#b1cccd",
  shadow: "#000000",
  source_color: "#478185",
  surface: "#f4fafb",
  surface_bright: "#f4fafb",
  surface_container: "#e9efef",
  surface_container_high: "#e3e9e9",
  surface_container_highest: "#dde4e4",
  surface_container_low: "#eff5f5",
  surface_container_lowest: "#ffffff",
  surface_dim: "#d5dbdb",
  surface_tint: "#00696e",
  surface_variant: "#dae4e5",
  tertiary: "#4e5f7d",
  tertiary_container: "#d6e3ff",
  tertiary_fixed: "#d6e3ff",
  tertiary_fixed_dim: "#b6c7e9"
};
